import {NextUIProvider} from "@nextui-org/react";
import LocksTable from "./page";
import './globals.css'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function App() {
  return (
    <html lang="en">
      <body >
        <NextUIProvider>
          <LocksTable />
        </NextUIProvider>
      </body>
    </html>
  );
}